
export const AUCTION_ADD_SUCCESS = 'AUCTION_ADD_SUCCESS';
export const AUCTION_ADD_ERROR = 'AUCTION_ADD_ERROR';
export const AUCTIONS_LOAD_SUCCESS = 'AUCTIONS_LOAD_SUCCESS';
export const AUCTIONS_LOAD_ERROR = 'AUCTIONS_LOAD_ERROR';
