
export const AUCTION_ADD_SUCCESS = 'AUCTION_ADD_SUCCESS';
export const AUCTION_ADD_ERROR = 'AUCTION_ADD_ERROR';
export const AUCTIONS_LOAD_SUCCESS = 'AUCTIONS_LOAD_SUCCESS';
export const AUCTIONS_LOAD_ERROR = 'AUCTIONS_LOAD_ERROR';
export const AUCTION_LOAD_SUCCESS = 'AUCTION_LOAD_SUCCESS';
export const AUCTION_LOAD_ERROR = 'AUCTION_LOAD_ERROR';
export const BID_UPDATE_SUCCESS = 'BID_UPDATE_SUCCESS';
export const BID_UPDATE_ERROR = 'BID_UPDATE_ERROR';
